/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Tic.Tac.Toe.app

fun main(){
    var game = TicTacToe()
    var result: Array<Array<String>> = game.move(2, 1)
    println(toString(result))
}
fun toString(grid: Array<Array<String>>): String {
    var result = ""
    for (i in grid.indices) {
        result += grid[i].joinToString(separator = ",") + "\n"
    }
    return result
}
